version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GRAFANA_URL=${GRAFANA_URL:-http://localhost:3000}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN:-}
      - PROMETHEUS_URL=${PROMETHEUS_URL:-http://localhost:9090}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-http://localhost:9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-}
      - NAGIOS_URL=${NAGIOS_URL:-http://localhost/nagios}
      - NAGIOS_USERNAME=${NAGIOS_USERNAME:-nagiosadmin}
      - NAGIOS_PASSWORD=${NAGIOS_PASSWORD:-}
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped